package questions

// WellKnownCountries is a starter set of widely recognizable countries for
// the flags and capitals categories. Source URLs point at each country's
// Wikipedia flag/overview page — stable, checkable references appropriate
// for a trivia game. This list is meant to grow over time; it is not
// exhaustive.
var WellKnownCountries = []Country{
	{ISO: "TR", NameTR: "Türkiye", NameEN: "Turkey", CapitalTR: "Ankara", CapitalEN: "Ankara",
		FlagSourceURL: "https://en.wikipedia.org/wiki/Flag_of_Turkey", CountrySourceURL: "https://en.wikipedia.org/wiki/Turkey"},
	{ISO: "DE", NameTR: "Almanya", NameEN: "Germany", CapitalTR: "Berlin", CapitalEN: "Berlin",
		FlagSourceURL: "https://en.wikipedia.org/wiki/Flag_of_Germany", CountrySourceURL: "https://en.wikipedia.org/wiki/Germany"},
	{ISO: "FR", NameTR: "Fransa", NameEN: "France", CapitalTR: "Paris", CapitalEN: "Paris",
		FlagSourceURL: "https://en.wikipedia.org/wiki/Flag_of_France", CountrySourceURL: "https://en.wikipedia.org/wiki/France"},
	{ISO: "IT", NameTR: "İtalya", NameEN: "Italy", CapitalTR: "Roma", CapitalEN: "Rome",
		FlagSourceURL: "https://en.wikipedia.org/wiki/Flag_of_Italy", CountrySourceURL: "https://en.wikipedia.org/wiki/Italy"},
	{ISO: "ES", NameTR: "İspanya", NameEN: "Spain", CapitalTR: "Madrid", CapitalEN: "Madrid",
		FlagSourceURL: "https://en.wikipedia.org/wiki/Flag_of_Spain", CountrySourceURL: "https://en.wikipedia.org/wiki/Spain"},
	{ISO: "GB", NameTR: "Birleşik Krallık", NameEN: "United Kingdom", CapitalTR: "Londra", CapitalEN: "London",
		FlagSourceURL: "https://en.wikipedia.org/wiki/Flag_of_the_United_Kingdom", CountrySourceURL: "https://en.wikipedia.org/wiki/United_Kingdom"},
	{ISO: "US", NameTR: "Amerika Birleşik Devletleri", NameEN: "United States", CapitalTR: "Washington D.C.", CapitalEN: "Washington, D.C.",
		FlagSourceURL: "https://en.wikipedia.org/wiki/Flag_of_the_United_States", CountrySourceURL: "https://en.wikipedia.org/wiki/United_States"},
	{ISO: "JP", NameTR: "Japonya", NameEN: "Japan", CapitalTR: "Tokyo", CapitalEN: "Tokyo",
		FlagSourceURL: "https://en.wikipedia.org/wiki/Flag_of_Japan", CountrySourceURL: "https://en.wikipedia.org/wiki/Japan"},
	{ISO: "CN", NameTR: "Çin", NameEN: "China", CapitalTR: "Pekin", CapitalEN: "Beijing",
		FlagSourceURL: "https://en.wikipedia.org/wiki/Flag_of_China", CountrySourceURL: "https://en.wikipedia.org/wiki/China"},
	{ISO: "RU", NameTR: "Rusya", NameEN: "Russia", CapitalTR: "Moskova", CapitalEN: "Moscow",
		FlagSourceURL: "https://en.wikipedia.org/wiki/Flag_of_Russia", CountrySourceURL: "https://en.wikipedia.org/wiki/Russia"},
	{ISO: "BR", NameTR: "Brezilya", NameEN: "Brazil", CapitalTR: "Brasília", CapitalEN: "Brasília",
		FlagSourceURL: "https://en.wikipedia.org/wiki/Flag_of_Brazil", CountrySourceURL: "https://en.wikipedia.org/wiki/Brazil"},
	{ISO: "CA", NameTR: "Kanada", NameEN: "Canada", CapitalTR: "Ottawa", CapitalEN: "Ottawa",
		FlagSourceURL: "https://en.wikipedia.org/wiki/Flag_of_Canada", CountrySourceURL: "https://en.wikipedia.org/wiki/Canada"},
	{ISO: "AU", NameTR: "Avustralya", NameEN: "Australia", CapitalTR: "Canberra", CapitalEN: "Canberra",
		FlagSourceURL: "https://en.wikipedia.org/wiki/Flag_of_Australia", CountrySourceURL: "https://en.wikipedia.org/wiki/Australia"},
	{ISO: "EG", NameTR: "Mısır", NameEN: "Egypt", CapitalTR: "Kahire", CapitalEN: "Cairo",
		FlagSourceURL: "https://en.wikipedia.org/wiki/Flag_of_Egypt", CountrySourceURL: "https://en.wikipedia.org/wiki/Egypt"},
	{ISO: "IN", NameTR: "Hindistan", NameEN: "India", CapitalTR: "Yeni Delhi", CapitalEN: "New Delhi",
		FlagSourceURL: "https://en.wikipedia.org/wiki/Flag_of_India", CountrySourceURL: "https://en.wikipedia.org/wiki/India"},
	{ISO: "MX", NameTR: "Meksika", NameEN: "Mexico", CapitalTR: "Meksika City", CapitalEN: "Mexico City",
		FlagSourceURL: "https://en.wikipedia.org/wiki/Flag_of_Mexico", CountrySourceURL: "https://en.wikipedia.org/wiki/Mexico"},
	{ISO: "KR", NameTR: "Güney Kore", NameEN: "South Korea", CapitalTR: "Seul", CapitalEN: "Seoul",
		FlagSourceURL: "https://en.wikipedia.org/wiki/Flag_of_South_Korea", CountrySourceURL: "https://en.wikipedia.org/wiki/South_Korea"},
	{ISO: "NL", NameTR: "Hollanda", NameEN: "Netherlands", CapitalTR: "Amsterdam", CapitalEN: "Amsterdam",
		FlagSourceURL: "https://en.wikipedia.org/wiki/Flag_of_the_Netherlands", CountrySourceURL: "https://en.wikipedia.org/wiki/Netherlands"},
	{ISO: "SE", NameTR: "İsveç", NameEN: "Sweden", CapitalTR: "Stockholm", CapitalEN: "Stockholm",
		FlagSourceURL: "https://en.wikipedia.org/wiki/Flag_of_Sweden", CountrySourceURL: "https://en.wikipedia.org/wiki/Sweden"},
	{ISO: "NO", NameTR: "Norveç", NameEN: "Norway", CapitalTR: "Oslo", CapitalEN: "Oslo",
		FlagSourceURL: "https://en.wikipedia.org/wiki/Flag_of_Norway", CountrySourceURL: "https://en.wikipedia.org/wiki/Norway"},
	{ISO: "GR", NameTR: "Yunanistan", NameEN: "Greece", CapitalTR: "Atina", CapitalEN: "Athens",
		FlagSourceURL: "https://en.wikipedia.org/wiki/Flag_of_Greece", CountrySourceURL: "https://en.wikipedia.org/wiki/Greece"},
	{ISO: "PT", NameTR: "Portekiz", NameEN: "Portugal", CapitalTR: "Lizbon", CapitalEN: "Lisbon",
		FlagSourceURL: "https://en.wikipedia.org/wiki/Flag_of_Portugal", CountrySourceURL: "https://en.wikipedia.org/wiki/Portugal"},
	{ISO: "PL", NameTR: "Polonya", NameEN: "Poland", CapitalTR: "Varşova", CapitalEN: "Warsaw",
		FlagSourceURL: "https://en.wikipedia.org/wiki/Flag_of_Poland", CountrySourceURL: "https://en.wikipedia.org/wiki/Poland"},
	{ISO: "AR", NameTR: "Arjantin", NameEN: "Argentina", CapitalTR: "Buenos Aires", CapitalEN: "Buenos Aires",
		FlagSourceURL: "https://en.wikipedia.org/wiki/Flag_of_Argentina", CountrySourceURL: "https://en.wikipedia.org/wiki/Argentina"},
}
