package questions

// WellKnownCountries is a starter set of widely recognizable countries for
// the flags and capitals categories. Source URLs point at each country's
// Wikipedia flag/overview page — stable, checkable references appropriate
// for a trivia game. This list is meant to grow over time; it is not
// exhaustive.
var WellKnownCountries = []Country{
	{ISO: "TR", NameTR: "Türkiye", NameEN: "Turkey", CapitalTR: "Ankara", CapitalEN: "Ankara",
		FlagSourceURL: "https://en.wikipedia.org/wiki/Flag_of_Turkey", CountrySourceURL: "https://en.wikipedia.org/wiki/Turkey"},
	{ISO: "DE", NameTR: "Almanya", NameEN: "Germany", CapitalTR: "Berlin", CapitalEN: "Berlin",
		FlagSourceURL: "https://en.wikipedia.org/wiki/Flag_of_Germany", CountrySourceURL: "https://en.wikipedia.org/wiki/Germany"},
	{ISO: "FR", NameTR: "Fransa", NameEN: "France", CapitalTR: "Paris", CapitalEN: "Paris",
		FlagSourceURL: "https://en.wikipedia.org/wiki/Flag_of_France", CountrySourceURL: "https://en.wikipedia.org/wiki/France"},
	{ISO: "IT", NameTR: "İtalya", NameEN: "Italy", CapitalTR: "Roma", CapitalEN: "Rome",
		FlagSourceURL: "https://en.wikipedia.org/wiki/Flag_of_Italy", CountrySourceURL: "https://en.wikipedia.org/wiki/Italy"},
	{ISO: "ES", NameTR: "İspanya", NameEN: "Spain", CapitalTR: "Madrid", CapitalEN: "Madrid",
		FlagSourceURL: "https://en.wikipedia.org/wiki/Flag_of_Spain", CountrySourceURL: "https://en.wikipedia.org/wiki/Spain"},
	{ISO: "GB", NameTR: "Birleşik Krallık", NameEN: "United Kingdom", CapitalTR: "Londra", CapitalEN: "London",
		FlagSourceURL: "https://en.wikipedia.org/wiki/Flag_of_the_United_Kingdom", CountrySourceURL: "https://en.wikipedia.org/wiki/United_Kingdom"},
	{ISO: "US", NameTR: "Amerika Birleşik Devletleri", NameEN: "United States", CapitalTR: "Washington D.C.", CapitalEN: "Washington, D.C.",
		FlagSourceURL: "https://en.wikipedia.org/wiki/Flag_of_the_United_States", CountrySourceURL: "https://en.wikipedia.org/wiki/United_States"},
	{ISO: "JP", NameTR: "Japonya", NameEN: "Japan", CapitalTR: "Tokyo", CapitalEN: "Tokyo",
		FlagSourceURL: "https://en.wikipedia.org/wiki/Flag_of_Japan", CountrySourceURL: "https://en.wikipedia.org/wiki/Japan"},
	{ISO: "CN", NameTR: "Çin", NameEN: "China", CapitalTR: "Pekin", CapitalEN: "Beijing",
		FlagSourceURL: "https://en.wikipedia.org/wiki/Flag_of_China", CountrySourceURL: "https://en.wikipedia.org/wiki/China"},
	{ISO: "RU", NameTR: "Rusya", NameEN: "Russia", CapitalTR: "Moskova", CapitalEN: "Moscow",
		FlagSourceURL: "https://en.wikipedia.org/wiki/Flag_of_Russia", CountrySourceURL: "https://en.wikipedia.org/wiki/Russia"},
	{ISO: "BR", NameTR: "Brezilya", NameEN: "Brazil", CapitalTR: "Brasília", CapitalEN: "Brasília",
		FlagSourceURL: "https://en.wikipedia.org/wiki/Flag_of_Brazil", CountrySourceURL: "https://en.wikipedia.org/wiki/Brazil"},
	{ISO: "CA", NameTR: "Kanada", NameEN: "Canada", CapitalTR: "Ottawa", CapitalEN: "Ottawa",
		FlagSourceURL: "https://en.wikipedia.org/wiki/Flag_of_Canada", CountrySourceURL: "https://en.wikipedia.org/wiki/Canada"},
	{ISO: "AU", NameTR: "Avustralya", NameEN: "Australia", CapitalTR: "Canberra", CapitalEN: "Canberra",
		FlagSourceURL: "https://en.wikipedia.org/wiki/Flag_of_Australia", CountrySourceURL: "https://en.wikipedia.org/wiki/Australia"},
	{ISO: "EG", NameTR: "Mısır", NameEN: "Egypt", CapitalTR: "Kahire", CapitalEN: "Cairo",
		FlagSourceURL: "https://en.wikipedia.org/wiki/Flag_of_Egypt", CountrySourceURL: "https://en.wikipedia.org/wiki/Egypt"},
	{ISO: "IN", NameTR: "Hindistan", NameEN: "India", CapitalTR: "Yeni Delhi", CapitalEN: "New Delhi",
		FlagSourceURL: "https://en.wikipedia.org/wiki/Flag_of_India", CountrySourceURL: "https://en.wikipedia.org/wiki/India"},
	{ISO: "MX", NameTR: "Meksika", NameEN: "Mexico", CapitalTR: "Meksika City", CapitalEN: "Mexico City",
		FlagSourceURL: "https://en.wikipedia.org/wiki/Flag_of_Mexico", CountrySourceURL: "https://en.wikipedia.org/wiki/Mexico"},
	{ISO: "KR", NameTR: "Güney Kore", NameEN: "South Korea", CapitalTR: "Seul", CapitalEN: "Seoul",
		FlagSourceURL: "https://en.wikipedia.org/wiki/Flag_of_South_Korea", CountrySourceURL: "https://en.wikipedia.org/wiki/South_Korea"},
	{ISO: "NL", NameTR: "Hollanda", NameEN: "Netherlands", CapitalTR: "Amsterdam", CapitalEN: "Amsterdam",
		FlagSourceURL: "https://en.wikipedia.org/wiki/Flag_of_the_Netherlands", CountrySourceURL: "https://en.wikipedia.org/wiki/Netherlands"},
	{ISO: "SE", NameTR: "İsveç", NameEN: "Sweden", CapitalTR: "Stockholm", CapitalEN: "Stockholm",
		FlagSourceURL: "https://en.wikipedia.org/wiki/Flag_of_Sweden", CountrySourceURL: "https://en.wikipedia.org/wiki/Sweden"},
	{ISO: "NO", NameTR: "Norveç", NameEN: "Norway", CapitalTR: "Oslo", CapitalEN: "Oslo",
		FlagSourceURL: "https://en.wikipedia.org/wiki/Flag_of_Norway", CountrySourceURL: "https://en.wikipedia.org/wiki/Norway"},
	{ISO: "GR", NameTR: "Yunanistan", NameEN: "Greece", CapitalTR: "Atina", CapitalEN: "Athens",
		FlagSourceURL: "https://en.wikipedia.org/wiki/Flag_of_Greece", CountrySourceURL: "https://en.wikipedia.org/wiki/Greece"},
	{ISO: "PT", NameTR: "Portekiz", NameEN: "Portugal", CapitalTR: "Lizbon", CapitalEN: "Lisbon",
		FlagSourceURL: "https://en.wikipedia.org/wiki/Flag_of_Portugal", CountrySourceURL: "https://en.wikipedia.org/wiki/Portugal"},
	{ISO: "PL", NameTR: "Polonya", NameEN: "Poland", CapitalTR: "Varşova", CapitalEN: "Warsaw",
		FlagSourceURL: "https://en.wikipedia.org/wiki/Flag_of_Poland", CountrySourceURL: "https://en.wikipedia.org/wiki/Poland"},
	{ISO: "AR", NameTR: "Arjantin", NameEN: "Argentina", CapitalTR: "Buenos Aires", CapitalEN: "Buenos Aires",
		FlagSourceURL: "https://en.wikipedia.org/wiki/Flag_of_Argentina", CountrySourceURL: "https://en.wikipedia.org/wiki/Argentina"},
	{ISO: "UA", NameTR: "Ukrayna", NameEN: "Ukraine", CapitalTR: "Kiev", CapitalEN: "Kyiv",
		FlagSourceURL: "https://en.wikipedia.org/wiki/Flag_of_Ukraine", CountrySourceURL: "https://en.wikipedia.org/wiki/Ukraine"},
	{ISO: "CH", NameTR: "İsviçre", NameEN: "Switzerland", CapitalTR: "Bern", CapitalEN: "Bern",
		FlagSourceURL: "https://en.wikipedia.org/wiki/Flag_of_Switzerland", CountrySourceURL: "https://en.wikipedia.org/wiki/Switzerland"},
	{ISO: "AT", NameTR: "Avusturya", NameEN: "Austria", CapitalTR: "Viyana", CapitalEN: "Vienna",
		FlagSourceURL: "https://en.wikipedia.org/wiki/Flag_of_Austria", CountrySourceURL: "https://en.wikipedia.org/wiki/Austria"},
	{ISO: "BE", NameTR: "Belçika", NameEN: "Belgium", CapitalTR: "Brüksel", CapitalEN: "Brussels",
		FlagSourceURL: "https://en.wikipedia.org/wiki/Flag_of_Belgium", CountrySourceURL: "https://en.wikipedia.org/wiki/Belgium"},
	{ISO: "IE", NameTR: "İrlanda", NameEN: "Ireland", CapitalTR: "Dublin", CapitalEN: "Dublin",
		FlagSourceURL: "https://en.wikipedia.org/wiki/Flag_of_Ireland", CountrySourceURL: "https://en.wikipedia.org/wiki/Ireland"},
	{ISO: "DK", NameTR: "Danimarka", NameEN: "Denmark", CapitalTR: "Kopenhag", CapitalEN: "Copenhagen",
		FlagSourceURL: "https://en.wikipedia.org/wiki/Flag_of_Denmark", CountrySourceURL: "https://en.wikipedia.org/wiki/Denmark"},
	{ISO: "FI", NameTR: "Finlandiya", NameEN: "Finland", CapitalTR: "Helsinki", CapitalEN: "Helsinki",
		FlagSourceURL: "https://en.wikipedia.org/wiki/Flag_of_Finland", CountrySourceURL: "https://en.wikipedia.org/wiki/Finland"},
	{ISO: "IS", NameTR: "İzlanda", NameEN: "Iceland", CapitalTR: "Reykjavik", CapitalEN: "Reykjavik",
		FlagSourceURL: "https://en.wikipedia.org/wiki/Flag_of_Iceland", CountrySourceURL: "https://en.wikipedia.org/wiki/Iceland"},
	{ISO: "NZ", NameTR: "Yeni Zelanda", NameEN: "New Zealand", CapitalTR: "Wellington", CapitalEN: "Wellington",
		FlagSourceURL: "https://en.wikipedia.org/wiki/Flag_of_New_Zealand", CountrySourceURL: "https://en.wikipedia.org/wiki/New_Zealand"},
	{ISO: "ID", NameTR: "Endonezya", NameEN: "Indonesia", CapitalTR: "Cakarta", CapitalEN: "Jakarta",
		FlagSourceURL: "https://en.wikipedia.org/wiki/Flag_of_Indonesia", CountrySourceURL: "https://en.wikipedia.org/wiki/Indonesia"},
	{ISO: "TH", NameTR: "Tayland", NameEN: "Thailand", CapitalTR: "Bangkok", CapitalEN: "Bangkok",
		FlagSourceURL: "https://en.wikipedia.org/wiki/Flag_of_Thailand", CountrySourceURL: "https://en.wikipedia.org/wiki/Thailand"},
	{ISO: "VN", NameTR: "Vietnam", NameEN: "Vietnam", CapitalTR: "Hanoi", CapitalEN: "Hanoi",
		FlagSourceURL: "https://en.wikipedia.org/wiki/Flag_of_Vietnam", CountrySourceURL: "https://en.wikipedia.org/wiki/Vietnam"},
	{ISO: "PH", NameTR: "Filipinler", NameEN: "Philippines", CapitalTR: "Manila", CapitalEN: "Manila",
		FlagSourceURL: "https://en.wikipedia.org/wiki/Flag_of_the_Philippines", CountrySourceURL: "https://en.wikipedia.org/wiki/Philippines"},
	{ISO: "MY", NameTR: "Malezya", NameEN: "Malaysia", CapitalTR: "Kuala Lumpur", CapitalEN: "Kuala Lumpur",
		FlagSourceURL: "https://en.wikipedia.org/wiki/Flag_of_Malaysia", CountrySourceURL: "https://en.wikipedia.org/wiki/Malaysia"},
	{ISO: "SG", NameTR: "Singapur", NameEN: "Singapore", CapitalTR: "Singapur", CapitalEN: "Singapore",
		FlagSourceURL: "https://en.wikipedia.org/wiki/Flag_of_Singapore", CountrySourceURL: "https://en.wikipedia.org/wiki/Singapore"},
	{ISO: "PK", NameTR: "Pakistan", NameEN: "Pakistan", CapitalTR: "İslamabad", CapitalEN: "Islamabad",
		FlagSourceURL: "https://en.wikipedia.org/wiki/Flag_of_Pakistan", CountrySourceURL: "https://en.wikipedia.org/wiki/Pakistan"},
	{ISO: "SA", NameTR: "Suudi Arabistan", NameEN: "Saudi Arabia", CapitalTR: "Riyad", CapitalEN: "Riyadh",
		FlagSourceURL: "https://en.wikipedia.org/wiki/Flag_of_Saudi_Arabia", CountrySourceURL: "https://en.wikipedia.org/wiki/Saudi_Arabia"},
	{ISO: "AE", NameTR: "Birleşik Arap Emirlikleri", NameEN: "United Arab Emirates", CapitalTR: "Abu Dabi", CapitalEN: "Abu Dhabi",
		FlagSourceURL: "https://en.wikipedia.org/wiki/Flag_of_the_United_Arab_Emirates", CountrySourceURL: "https://en.wikipedia.org/wiki/United_Arab_Emirates"},
	{ISO: "IL", NameTR: "İsrail", NameEN: "Israel", CapitalTR: "Kudüs", CapitalEN: "Jerusalem",
		FlagSourceURL: "https://en.wikipedia.org/wiki/Flag_of_Israel", CountrySourceURL: "https://en.wikipedia.org/wiki/Israel"},
	{ISO: "IR", NameTR: "İran", NameEN: "Iran", CapitalTR: "Tahran", CapitalEN: "Tehran",
		FlagSourceURL: "https://en.wikipedia.org/wiki/Flag_of_Iran", CountrySourceURL: "https://en.wikipedia.org/wiki/Iran"},
	{ISO: "NG", NameTR: "Nijerya", NameEN: "Nigeria", CapitalTR: "Abuja", CapitalEN: "Abuja",
		FlagSourceURL: "https://en.wikipedia.org/wiki/Flag_of_Nigeria", CountrySourceURL: "https://en.wikipedia.org/wiki/Nigeria"},
	{ISO: "ZA", NameTR: "Güney Afrika", NameEN: "South Africa", CapitalTR: "Pretoria", CapitalEN: "Pretoria",
		FlagSourceURL: "https://en.wikipedia.org/wiki/Flag_of_South_Africa", CountrySourceURL: "https://en.wikipedia.org/wiki/South_Africa"},
	{ISO: "KE", NameTR: "Kenya", NameEN: "Kenya", CapitalTR: "Nairobi", CapitalEN: "Nairobi",
		FlagSourceURL: "https://en.wikipedia.org/wiki/Flag_of_Kenya", CountrySourceURL: "https://en.wikipedia.org/wiki/Kenya"},
	{ISO: "MA", NameTR: "Fas", NameEN: "Morocco", CapitalTR: "Rabat", CapitalEN: "Rabat",
		FlagSourceURL: "https://en.wikipedia.org/wiki/Flag_of_Morocco", CountrySourceURL: "https://en.wikipedia.org/wiki/Morocco"},
	{ISO: "CO", NameTR: "Kolombiya", NameEN: "Colombia", CapitalTR: "Bogota", CapitalEN: "Bogotá",
		FlagSourceURL: "https://en.wikipedia.org/wiki/Flag_of_Colombia", CountrySourceURL: "https://en.wikipedia.org/wiki/Colombia"},
	{ISO: "CL", NameTR: "Şili", NameEN: "Chile", CapitalTR: "Santiago", CapitalEN: "Santiago",
		FlagSourceURL: "https://en.wikipedia.org/wiki/Flag_of_Chile", CountrySourceURL: "https://en.wikipedia.org/wiki/Chile"},
	{ISO: "PE", NameTR: "Peru", NameEN: "Peru", CapitalTR: "Lima", CapitalEN: "Lima",
		FlagSourceURL: "https://en.wikipedia.org/wiki/Flag_of_Peru", CountrySourceURL: "https://en.wikipedia.org/wiki/Peru"},
	{ISO: "CU", NameTR: "Küba", NameEN: "Cuba", CapitalTR: "Havana", CapitalEN: "Havana",
		FlagSourceURL: "https://en.wikipedia.org/wiki/Flag_of_Cuba", CountrySourceURL: "https://en.wikipedia.org/wiki/Cuba"},
}
